#!/bin/bash
# 验证 src/compile.sh 在 multi-file bootstrap 路径下只清理 Uya 生成的 split-C 产物，
# 不会递归删除目录里的外来 .c/.h/Makefile。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILE_SH="$REPO_ROOT/src/compile.sh"
TMP_DIR="$(mktemp -d /tmp/uya_compile_sh_cleanup.XXXXXX)"
CACHE_DIR="$TMP_DIR/shared-cache"
LOG_FILE="$TMP_DIR/compile.log"

cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

if [ ! -x "$COMPILE_SH" ]; then
    echo "✗ 未找到 compile.sh: $COMPILE_SH"
    exit 1
fi

mkdir -p "$CACHE_DIR/nested"
printf '%s\n' '# Generated by Uya --split-c-dir' >"$CACHE_DIR/Makefile"
printf '%s\n' 'nested/generated.o: nested/generated.c uya_part1_types.h uya_split_protos.h' >>"$CACHE_DIR/Makefile"
printf '%s\n' 'uya_part1.o: uya_part1.c uya_strings_extern.h' >>"$CACHE_DIR/Makefile"
printf '%s\n' 'all:' >>"$CACHE_DIR/Makefile"
printf '%s\n' 'keep source' >"$CACHE_DIR/keep.c"
printf '%s\n' 'keep header' >"$CACHE_DIR/keep.h"
printf '%s\n' 'generated source' >"$CACHE_DIR/nested/generated.c"
printf '%s\n' 'generated header' >"$CACHE_DIR/uya_part1_types.h"
printf '%s\n' 'generated proto' >"$CACHE_DIR/uya_split_protos.h"
printf '%s\n' 'generated strings' >"$CACHE_DIR/uya_strings_extern.h"
printf '%s\n' 'generated part1' >"$CACHE_DIR/uya_part1.c"
printf '%s\n' 'generated object' >"$CACHE_DIR/nested/generated.o"

echo "验证：compile.sh 清理 split-C 旧缓存时保留目录里的外来源码文件 ..."

set +e
(
    cd "$REPO_ROOT/src"
    UYA_COMPILER=/bin/false \
    UYA_MULTI_FILE_C=1 \
    UYA_SPLIT_C_DIR="$CACHE_DIR" \
    UYA_SPLIT_C=0 \
    ./compile.sh --c99 -e --name cleanup-safety-check >"$LOG_FILE" 2>&1
)
STATUS=$?
set -e

if [ "$STATUS" -eq 0 ]; then
    echo "✗ 测试期望 compile.sh 在调用 /bin/false 时失败，但它成功了"
    cat "$LOG_FILE"
    exit 1
fi

if [ ! -f "$CACHE_DIR/keep.c" ] || [ ! -f "$CACHE_DIR/keep.h" ]; then
    echo "✗ compile.sh 清理时误删了外来源码文件"
    find "$CACHE_DIR" -maxdepth 2 -type f | sort
    cat "$LOG_FILE"
    exit 1
fi

if [ -f "$CACHE_DIR/nested/generated.c" ] || [ -f "$CACHE_DIR/uya_part1_types.h" ] || [ -f "$CACHE_DIR/uya_part1.c" ] || [ -f "$CACHE_DIR/nested/generated.o" ]; then
    echo "✗ compile.sh 未清掉 Makefile 中列出的旧 split-C 生成物"
    find "$CACHE_DIR" -maxdepth 2 -type f | sort
    cat "$LOG_FILE"
    exit 1
fi

if [ -f "$CACHE_DIR/Makefile" ]; then
    echo "✗ compile.sh 未清掉旧的生成 Makefile"
    find "$CACHE_DIR" -maxdepth 2 -type f | sort
    cat "$LOG_FILE"
    exit 1
fi

echo "verify_compile_sh_split_cache_cleanup: ok"
